/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    DialogDelete: typeof import('./src/components/dialogs/DialogDelete.vue')['default']
    DialogTaskFields: typeof import('./src/components/dialogs/DialogTaskFields.vue')['default']
    ListTasks: typeof import('./src/components/ListTasks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToDoList: typeof import('./src/components/ToDoList.vue')['default']
  }
}
